/**
 * Controls whether parameter values are exposed in driver observer events.
 */
export type AshibaMaskPolicy = 'always' | 'development' | 'never';

/**
 * Stable identity fields that make SQL execution events traceable by applications.
 */
export type AshibaSqlExecutionMetadata = {
  sqlId?: string;
  queryId?: string;
  requestId?: string;
  apiMethod?: string;
  apiPath?: string;
  apiRoute?: string;
  operation?: string;
  filterKeys?: readonly string[];
  sortKeys?: readonly string[];
  queryVariant?: string;
  queryModelSourceHash?: string;
  queryModelStatementKind?: string;
  queryModelRootQueryShape?: string;
  queryModelOptionalConditionCompression?: boolean;
  queryModelSafeSortInsertionStatus?: string;
  sqlFile?: string;
  sqlPath?: string;
  dialect?: string;
};

/**
 * Structured event emitted by optional Ashiba driver adapters around SQL execution.
 */
export type AshibaSqlExecutionEvent = {
  phase: 'start' | 'end' | 'error';
  executionId?: string;
  metadata?: AshibaSqlExecutionMetadata;
  warnings?: readonly {
    code: string;
    message: string;
    nextAction?: string;
  }[];
  sourceSql?: string;
  compiledSql?: string;
  parameterNames?: readonly string[];
  maskedParams?: readonly unknown[];
  params?: readonly unknown[];
  elapsedMs?: number;
  rowCount?: number;
  error?: {
    name: string;
    message: string;
    code?: string;
    cause?: string;
    nextAction?: string;
  };
};

/**
 * Application-provided observer hook for integrating Ashiba driver events with a logger.
 */
export type AshibaSqlExecutionObserver = {
  emit(event: AshibaSqlExecutionEvent): void;
};

/**
 * Allowed direction values for safe sort rendering.
 */
export type AshibaSortDirection = 'asc' | 'desc';

/**
 * One reviewed SQL expression exposed as a safe sort key.
 */
export type AshibaSortProfileEntry = {
  sql: string;
  defaultDirection?: AshibaSortDirection;
  allowedDirections?: readonly AshibaSortDirection[];
};

/**
 * Runtime-visible safe sort dictionary keyed by public sort names.
 */
export type AshibaSortProfile = Readonly<Record<string, AshibaSortProfileEntry>>;

/**
 * Sort request supplied by application code after user input has been mapped to a sort key.
 */
export type AshibaSortInput = {
  key: string;
  direction?: AshibaSortDirection;
};

/**
 * CLI-generated query metadata used by runtime adapters without parsing SQL at runtime.
 */
export type AshibaQueryModelAnalysis = {
  astParse: 'ok' | 'failed';
  statementKind: 'select' | 'insert' | 'update' | 'delete' | 'unknown';
  rootQueryShape?: 'simple-select' | 'compound-select' | 'values' | 'non-select' | 'unknown';
  hasTopLevelOrderBy: boolean | 'unknown';
  parserCapabilities?: {
    parser: {
      status: 'supported' | 'degraded';
      reason?: string;
    };
    sqlStorage: 'unaffected';
    execution: 'unaffected';
    parameterBinding: 'unaffected';
    logging: 'unaffected';
    resultContract: 'supported' | 'degraded';
    optionalConditionCompression: 'supported' | 'blocked';
    safeSort: 'supported' | 'blocked';
    impactAnalysis: 'supported' | 'degraded';
  };
  sourceHash?: string;
  safeSort?: {
    insertion:
      | {
        status: 'ready';
        index: number;
        end?: number;
        mode: 'order-by' | 'prepend-comma' | 'comma' | 'replace';
      }
      | {
        status: 'unresolved';
        reason?: string;
      };
    sortable?: Readonly<Record<string, AshibaSortProfileEntry>>;
  };
  optionalConditionCompression?: {
    enabled: true;
    branches: readonly {
      parameterName: string;
      kind: 'expression';
      sourceRange: {
        start: number;
        end: number;
        text?: string;
      };
      removalRange: {
        start: number;
        end: number;
        text?: string;
      };
      presentReplacement: {
        start: number;
        end: number;
        text: string;
      };
    }[];
    groups?: readonly {
      branchIndexes: readonly number[];
      removalRange: {
        start: number;
        end: number;
        text?: string;
      };
      leadingPrefixes?: readonly {
        branchIndexes: readonly number[];
        removalRange: {
          start: number;
          end: number;
          text?: string;
        };
      }[];
    }[];
  };
};

/**
 * Dialect-specific SQL and parameter binding metadata generated by the CLI.
 */
export type FeatureQueryDialectBinding = { sourceHash?: string } & (
  | { style: 'indexed'; sql: string; parameterNames: readonly string[] }
  | { style: 'named'; sql: string; parameterNames: readonly string[] }
  | { style: 'anonymous'; sql: string; valueNames: readonly string[] }
);

/** Evidence level attached to one generated query-contract fact. */
export type AshibaQueryContractProvenance = 'proven' | 'inferred' | 'driver-mapped' | 'unknown';

/** PostgreSQL catalog classification retained independently from TypeScript values. */
export type PostgresDatabaseTypeKind =
  | 'base'
  | 'array'
  | 'enum'
  | 'domain'
  | 'composite'
  | 'range'
  | 'multirange'
  | 'pseudo'
  | 'unknown';

export type PostgresDomainConstraint = {
  name: string;
  definition: string;
  validated: boolean;
};

/** Cluster-independent PostgreSQL type identity for deterministic snapshot comparison. */
export type PostgresPortableDatabaseTypeIdentity = {
  schema: string;
  name: string;
  formattedName: string;
  kind: PostgresDatabaseTypeKind;
  category: string;
  typeModifier?: number;
  elementType?: PostgresPortableDatabaseTypeIdentity;
  baseType?: PostgresPortableDatabaseTypeIdentity;
  enumValues?: readonly string[];
  domainConstraints?: readonly PostgresDomainConstraint[];
};

/** PostgreSQL type identity reported by the development-time database oracle. */
export type PostgresDatabaseTypeIdentity = {
  oid: number;
  schema: string;
  name: string;
  formattedName: string;
  kind: PostgresDatabaseTypeKind;
  category: string;
  elementTypeOid?: number;
  baseTypeOid?: number;
  enumValues?: readonly string[];
  typeModifier?: number;
  domainConstraints?: readonly PostgresDomainConstraint[];
  portableIdentity?: PostgresPortableDatabaseTypeIdentity;
};

/** Nullability evidence kept separate because PostgreSQL result type metadata does not generally prove it. */
export type PostgresContractNullability = {
  value: 'non-null' | 'nullable' | 'unknown';
  provenance: Extract<AshibaQueryContractProvenance, 'inferred' | 'unknown'>;
};

/** One PostgreSQL-derived parameter position. */
export type PostgresContractParameter = {
  position: number;
  name?: string;
  databaseType: PostgresDatabaseTypeIdentity;
  typeProvenance: Extract<AshibaQueryContractProvenance, 'proven'>;
  nullability: PostgresContractNullability;
  typeModifier?: number;
};

/** One PostgreSQL-derived result position. */
export type PostgresContractResult = {
  position: number;
  name?: string;
  nameProvenance: Extract<AshibaQueryContractProvenance, 'proven' | 'inferred' | 'unknown'>;
  databaseType: PostgresDatabaseTypeIdentity;
  typeProvenance: Extract<AshibaQueryContractProvenance, 'proven'>;
  nullability: PostgresContractNullability;
};

/** Public identifier for the driver representation assumed by generated metadata. */
export type PostgresDriverRepresentationProfile = 'node-postgres-default' | `custom:${string}`;

/** Driver-side value representation, deliberately separate from the PostgreSQL database type. */
export type PostgresDriverRepresentation = {
  position: number;
  name?: string;
  runtimeType:
    | 'number'
    | 'string'
    | 'boolean'
    | 'Date'
    | 'array'
    | 'json-value'
    | 'unknown';
  typeScriptType: string;
  provenance: Extract<AshibaQueryContractProvenance, 'driver-mapped' | 'unknown'>;
};

export type PostgresQueryDependency = {
  kind: 'column' | 'relation' | 'function';
  schema: string;
  name: string;
  relationKind?: string;
  column?: string;
  columnNotNull?: boolean;
  columnType?: PostgresPortableDatabaseTypeIdentity;
  columnTypeModifier?: number;
  definitionHash?: string;
  identityArguments?: string;
  resultType?: string;
};

/** Deterministic, optional development-time PostgreSQL query contract. */
export type PostgresDerivedQueryContract = {
  version: 1;
  sourceHash: string;
  database: {
    system: 'postgresql';
    serverMajor: number;
    parameters: readonly PostgresContractParameter[];
    results: readonly PostgresContractResult[];
    dependencies?: readonly PostgresQueryDependency[];
  };
  driver: {
    profile: PostgresDriverRepresentationProfile;
    parameters: readonly PostgresDriverRepresentation[];
    results: readonly PostgresDriverRepresentation[];
  };
  diagnostics: readonly {
    code: string;
    message: string;
  }[];
};

/** Minimal contract evidence required by the application runtime. */
export type PostgresRuntimeQueryContract = {
  version: 1;
  sourceHash: string;
  driver: {
    profile: PostgresDriverRepresentationProfile;
  };
};

/**
 * PostgreSQL binding metadata used by safe sort and optional-condition rewrites.
 */
export type FeatureQueryPostgresDialectBinding = { sourceHash?: string; style: 'indexed'; sql: string; parameterNames: readonly string[] } & {
  /** Runtime-only summary of the optional database-derived development contract. */
  contract?: PostgresRuntimeQueryContract;
  safeSortInsertion?: {
    index: number;
    end?: number;
  };
  optionalConditionCompression?: {
    branches: readonly {
      parameterName: string;
      removalRange: {
        start: number;
        end: number;
        text?: string;
      };
      presentReplacement: {
        start: number;
        end: number;
        text: string;
      };
    }[];
    groups?: readonly {
      branchIndexes: readonly number[];
      removalRange: {
        start: number;
        end: number;
        text?: string;
      };
      leadingPrefixes?: readonly {
        branchIndexes: readonly number[];
        removalRange: {
          start: number;
          end: number;
          text?: string;
        };
      }[];
    }[];
  };
};

/**
 * Dialect binding slots known by the shared feature query model.
 */
export type FeatureQueryDialectBindings = {
  postgres?: FeatureQueryPostgresDialectBinding;
  mysql2?: FeatureQueryDialectBinding;
  mssql?: FeatureQueryDialectBinding;
  sqlite?: FeatureQueryDialectBinding;
};

/**
 * Query model shape consumed by feature-level query boundaries.
 *
 * This is intentionally a contract type, not an ORM model. The SQL file remains
 * the canonical source; generated metadata and runtime snapshots only prove that
 * an optional Ashiba adapter is executing the reviewed SQL contract.
 */
export type FeatureQueryModel = {
  analysis: AshibaQueryModelAnalysis & {
    /** Source-order result names when development-time AST extraction can prove them. */
    resultColumnOrder?: readonly string[];
    resultColumnTypes?: Record<string, string>;
    resultColumnNullability?: Record<string, 'non-null' | 'nullable' | 'unknown'>;
    parameterTypes?: Record<string, string>;
  };
  bindings?: FeatureQueryDialectBindings;
};

/**
 * Type-only contract carried by an application-supplied SQL text source.
 *
 * The invariant function properties prevent callers from substituting an
 * unrelated Params or Row type through an explicit generic argument. The
 * property is optional so generated runtime artifacts do not need to emit a
 * value: a normal type annotation is enough to bind the source to its contract.
 */
export interface AshibaTypedQuerySource<Params extends object = Record<string, unknown>, Row = unknown> {
  readonly __ashibaContract?: {
    readonly params: (value: Params) => Params;
    readonly row: (value: Row) => Row;
  };
}

/** Extract the parameter object bound to a typed Ashiba query source. */
export type AshibaQueryParams<Query> = Query extends AshibaTypedQuerySource<infer Params, infer _Row>
  ? Params
  : never;

/** Extract the row object bound to a typed Ashiba query source. */
export type AshibaQueryRow<Query> = Query extends AshibaTypedQuerySource<infer _Params, infer Row>
  ? Row
  : never;

/** Runtime fields shared by every feature query source. */
export interface FeatureQuerySourceBase {
  id: string;
  path: string;
  /** Optional application/build-tool provenance for the supplied SQL text. */
  sqlPath?: string;
  sql: string;
  queryModel: FeatureQueryModel;
  optionalConditionCompression?: boolean;
  metadata?: AshibaSqlExecutionMetadata;
}

/**
 * SQL text plus its mechanically checked Params/Row contract.
 */
export interface FeatureQuerySource<Params extends object = Record<string, unknown>, Row = unknown>
  extends FeatureQuerySourceBase, AshibaTypedQuerySource<Params, Row> {}

/** Any typed feature query source while preserving its concrete contract. */
export type AnyFeatureQuerySource = FeatureQuerySourceBase & AshibaTypedQuerySource<any, any>;

/**
 * Optional feature-level SQL execution convenience boundary.
 *
 * Feature and workflow code depend on this instead of pg, logger packages, or
 * concrete adapter implementations.
 */
export interface FeatureQueryExecutor<Query extends AnyFeatureQuerySource = AnyFeatureQuerySource> {
  query(
    query: Query,
    params: AshibaQueryParams<Query>,
  ): Promise<AshibaQueryRow<Query>[]>;
}

/**
 * Error raised when a feature query boundary receives a row count that does
 * not match the helper-selected cardinality contract.
 */
export class FeatureQueryCardinalityError extends Error {
  readonly code: 'ASHIBA_QUERY_EXPECTED_ONE_ROW' | 'ASHIBA_QUERY_EXPECTED_ZERO_OR_ONE_ROW';
  readonly queryId: string;
  readonly rowCount: number;
  readonly causeText: string;
  readonly nextAction: string;
  readonly details: { queryId: string; rowCount: number };

  constructor(code: FeatureQueryCardinalityError['code'], query: FeatureQuerySource, rowCount: number) {
    const expected = code === 'ASHIBA_QUERY_EXPECTED_ONE_ROW' ? 'one row' : 'zero or one row';
    super(`${query.id} query expected ${expected}, but got ${rowCount}.`);
    this.name = 'FeatureQueryCardinalityError';
    this.code = code;
    this.queryId = query.id;
    this.rowCount = rowCount;
    this.causeText = 'The selected feature query cardinality helper received a row count outside its contract.';
    this.nextAction = code === 'ASHIBA_QUERY_EXPECTED_ONE_ROW'
      ? 'Use queryMany for mutation workflows that need to handle zero rows, or use queryOne only when the SQL contract really guarantees exactly one row.'
      : 'Use queryMany when multiple rows are valid, or tighten the SQL so queryOneOrNull can only receive zero or one row.';
    this.details = { queryId: query.id, rowCount };
  }
}

/**
 * Execute a feature query and return every row.
 */
export async function queryMany<Query extends AnyFeatureQuerySource>(
  executor: FeatureQueryExecutor<Query>,
  query: Query,
  params: AshibaQueryParams<Query>,
): Promise<AshibaQueryRow<Query>[]> {
  return executor.query(query, params);
}

/**
 * Execute a feature query that must return exactly one row.
 */
export async function queryOne<Query extends AnyFeatureQuerySource>(
  executor: FeatureQueryExecutor<Query>,
  query: Query,
  params: AshibaQueryParams<Query>,
): Promise<AshibaQueryRow<Query>> {
  const rows = await queryMany(executor, query, params);
  if (rows.length !== 1) {
    throw new FeatureQueryCardinalityError('ASHIBA_QUERY_EXPECTED_ONE_ROW', query, rows.length);
  }
  return rows[0];
}

/**
 * Execute a feature query that may return no row, but must not return many.
 */
export async function queryOneOrNull<Query extends AnyFeatureQuerySource>(
  executor: FeatureQueryExecutor<Query>,
  query: Query,
  params: AshibaQueryParams<Query>,
): Promise<AshibaQueryRow<Query> | null> {
  const rows = await queryMany(executor, query, params);
  if (rows.length > 1) {
    throw new FeatureQueryCardinalityError('ASHIBA_QUERY_EXPECTED_ZERO_OR_ONE_ROW', query, rows.length);
  }
  return rows[0] ?? null;
}

/**
 * Error raised when a safe sort request violates the reviewed query model or sort profile.
 */
export class AshibaSortError extends Error {
  readonly code:
    | 'ASHIBA_UNKNOWN_SORT_KEY'
    | 'ASHIBA_DUPLICATE_SORT_KEY'
    | 'ASHIBA_INVALID_SORT_DIRECTION'
    | 'ASHIBA_EMPTY_SORT_PROFILE'
    | 'ASHIBA_SORT_QUERY_MODEL_REQUIRED'
    | 'ASHIBA_SORT_UNSUPPORTED_QUERY_MODEL'
    | 'ASHIBA_SORT_QUERY_MODEL_STALE'
    | 'ASHIBA_SORT_INSERTION_UNRESOLVED'
    | 'ASHIBA_SORT_PROFILE_OUTSIDE_QUERY_MODEL';
  readonly causeText: string;
  readonly nextAction: string;

  constructor(code: AshibaSortError['code'], message: string) {
    super(message);
    this.name = 'AshibaSortError';
    this.code = code;
    this.causeText = describeSortErrorCause(code);
    this.nextAction = describeSortErrorNextAction(code);
  }
}

/**
 * Return parameter values according to the requested event masking policy.
 */
export function maskParams(values: readonly unknown[], policy: AshibaMaskPolicy = 'always'): readonly unknown[] | undefined {
  if (policy === 'never') return values;
  return values.map(maskValue);
}

/**
 * Render an ORDER BY clause from a reviewed safe sort profile and validated sort input.
 */
export function renderSafeOrderBy(profile: AshibaSortProfile, input: readonly AshibaSortInput[]): string {
  if (input.length === 0) return '';
  if (Object.keys(profile).length === 0) {
    throw new AshibaSortError('ASHIBA_EMPTY_SORT_PROFILE', 'Sort profile is empty.');
  }

  const seen = new Set<string>();
  const fragments = input.map((item) => {
    const entry = profile[item.key];
    if (!entry) {
      throw new AshibaSortError('ASHIBA_UNKNOWN_SORT_KEY', `Unknown sort key: ${item.key}`);
    }
    if (seen.has(item.key)) {
      throw new AshibaSortError('ASHIBA_DUPLICATE_SORT_KEY', `Duplicate sort key: ${item.key}`);
    }
    seen.add(item.key);

    const direction = item.direction ?? entry.defaultDirection ?? 'asc';
    if (direction !== 'asc' && direction !== 'desc') {
      throw new AshibaSortError('ASHIBA_INVALID_SORT_DIRECTION', `Invalid sort direction for ${item.key}.`);
    }
    if (entry.allowedDirections && !entry.allowedDirections.includes(direction)) {
      throw new AshibaSortError(
        'ASHIBA_INVALID_SORT_DIRECTION',
        `Sort direction ${direction} for ${item.key} is not present in the reviewed source SQL ORDER BY.`,
      );
    }

    return `${entry.sql} ${direction}`;
  });

  return `order by ${fragments.join(', ')}`;
}

/**
 * Convert unknown thrown values into the structured error shape used by driver events.
 */
export function normalizeError(error: unknown): { name: string; message: string; code?: string; cause?: string; nextAction?: string } {
  if (error instanceof Error) {
    const maybeCode = 'code' in error && typeof error.code === 'string' ? error.code : undefined;
    const cause = 'causeText' in error && typeof error.causeText === 'string' ? error.causeText : undefined;
    const nextAction = 'nextAction' in error && typeof error.nextAction === 'string' ? error.nextAction : undefined;
    return {
      name: error.name,
      message: error.message,
      ...(maybeCode ? { code: maybeCode } : {}),
      ...(cause ? { cause } : {}),
      ...(nextAction ? { nextAction } : {}),
    };
  }

  return {
    name: 'Error',
    message: String(error),
  };
}

function describeSortErrorCause(code: AshibaSortError['code']): string {
  switch (code) {
    case 'ASHIBA_EMPTY_SORT_PROFILE':
      return 'Safe sort was requested, but no reviewed sortable keys are available.';
    case 'ASHIBA_UNKNOWN_SORT_KEY':
      return 'The requested sort key is not present in the reviewed safe sort profile.';
    case 'ASHIBA_DUPLICATE_SORT_KEY':
      return 'The same reviewed sort key was requested more than once.';
    case 'ASHIBA_INVALID_SORT_DIRECTION':
      return 'The requested sort direction is outside the allowed asc/desc values.';
    case 'ASHIBA_SORT_QUERY_MODEL_REQUIRED':
      return 'Safe sort requires CLI-generated query model metadata so the driver does not parse SQL at runtime.';
    case 'ASHIBA_SORT_UNSUPPORTED_QUERY_MODEL':
      return 'The query model shape is not supported for driver-side safe sort rendering.';
    case 'ASHIBA_SORT_QUERY_MODEL_STALE':
      return 'The query model metadata does not match the SQL being executed or is missing required dialect metadata.';
    case 'ASHIBA_SORT_INSERTION_UNRESOLVED':
      return 'The query model does not contain a resolved ORDER BY insertion position.';
    case 'ASHIBA_SORT_PROFILE_OUTSIDE_QUERY_MODEL':
      return 'The runtime sort profile attempted to use SQL outside the CLI-generated sortable metadata.';
  }
}

function describeSortErrorNextAction(code: AshibaSortError['code']): string {
  switch (code) {
    case 'ASHIBA_EMPTY_SORT_PROFILE':
      return 'Regenerate query model metadata with safe-sort analysis or disable safe sort for this query.';
    case 'ASHIBA_UNKNOWN_SORT_KEY':
      return 'Use one of the sortable keys recorded in the query model, or update the SQL and regenerate metadata.';
    case 'ASHIBA_DUPLICATE_SORT_KEY':
      return 'Provide each reviewed sort key at most once.';
    case 'ASHIBA_INVALID_SORT_DIRECTION':
      return 'Use asc or desc for the requested sort direction.';
    case 'ASHIBA_SORT_QUERY_MODEL_REQUIRED':
      return 'Run model generation for the visible SQL and pass the resulting query model to the driver adapter.';
    case 'ASHIBA_SORT_UNSUPPORTED_QUERY_MODEL':
      return 'Rewrite the SQL into a supported shape, such as wrapping a compound query in an explicit subquery, then regenerate metadata.';
    case 'ASHIBA_SORT_QUERY_MODEL_STALE':
      return 'Regenerate query model metadata from the current visible SQL and pass the matching dialect binding metadata.';
    case 'ASHIBA_SORT_INSERTION_UNRESOLVED':
      return 'Review the unsupported SQL shape, adjust it if needed, and regenerate query model metadata before enabling safe sort.';
    case 'ASHIBA_SORT_PROFILE_OUTSIDE_QUERY_MODEL':
      return 'Use the SQL expressions recorded in the query model sortable dictionary, or regenerate metadata after changing the visible SQL.';
  }
}

function maskValue(value: unknown): string {
  if (value === null || value === undefined) return '<nullish>';
  return '<masked>';
}
