import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import type { SqlFormatterOptions } from 'rawsql-ts';
import { invalidCliInputError } from './errors.js';

const SQL_KEYWORDS_REQUIRING_IDENTIFIER_QUOTES = new Set([
  'abort',
  'absolute',
  'access',
  'action',
  'add',
  'admin',
  'after',
  'aggregate',
  'all',
  'also',
  'alter',
  'always',
  'analyse',
  'analyze',
  'and',
  'any',
  'array',
  'as',
  'asc',
  'assertion',
  'assignment',
  'asymmetric',
  'at',
  'attach',
  'attribute',
  'authorization',
  'backward',
  'before',
  'begin',
  'between',
  'bigint',
  'binary',
  'bit',
  'boolean',
  'both',
  'by',
  'cache',
  'call',
  'called',
  'case',
  'cascade',
  'cascaded',
  'cast',
  'catalog',
  'chain',
  'char',
  'character',
  'characteristics',
  'check',
  'checkpoint',
  'class',
  'close',
  'cluster',
  'coalesce',
  'collate',
  'collation',
  'column',
  'columns',
  'comment',
  'comments',
  'commit',
  'committed',
  'compression',
  'concurrently',
  'configuration',
  'conflict',
  'connection',
  'constraint',
  'constraints',
  'content',
  'continue',
  'conversion',
  'copy',
  'cost',
  'create',
  'cross',
  'csv',
  'cube',
  'current',
  'current_catalog',
  'current_date',
  'current_role',
  'current_schema',
  'current_time',
  'current_timestamp',
  'current_user',
  'cursor',
  'cycle',
  'data',
  'database',
  'day',
  'deallocate',
  'dec',
  'decimal',
  'declare',
  'default',
  'defaults',
  'deferrable',
  'deferred',
  'definer',
  'delete',
  'delimiter',
  'delimiters',
  'desc',
  'detach',
  'dictionary',
  'disable',
  'discard',
  'distinct',
  'do',
  'document',
  'domain',
  'double',
  'drop',
  'each',
  'else',
  'enable',
  'encoding',
  'encrypted',
  'end',
  'enum',
  'escape',
  'event',
  'except',
  'exclude',
  'excluding',
  'exclusive',
  'execute',
  'exists',
  'explain',
  'expression',
  'extension',
  'external',
  'extract',
  'false',
  'family',
  'fetch',
  'filter',
  'finalize',
  'first',
  'float',
  'following',
  'force',
  'foreign',
  'forward',
  'freeze',
  'from',
  'full',
  'function',
  'functions',
  'generated',
  'global',
  'grant',
  'granted',
  'greatest',
  'group',
  'groups',
  'handler',
  'having',
  'header',
  'hold',
  'hour',
  'identity',
  'if',
  'ilike',
  'immediate',
  'immutable',
  'implicit',
  'import',
  'in',
  'include',
  'including',
  'increment',
  'index',
  'indexes',
  'inherit',
  'inherits',
  'initially',
  'inline',
  'inner',
  'inout',
  'input',
  'insert',
  'insensitive',
  'instead',
  'int',
  'integer',
  'intersect',
  'interval',
  'into',
  'invoker',
  'is',
  'isnull',
  'isolation',
  'join',
  'key',
  'language',
  'large',
  'last',
  'lateral',
  'leading',
  'leakproof',
  'least',
  'left',
  'level',
  'like',
  'limit',
  'listen',
  'load',
  'local',
  'localtime',
  'localtimestamp',
  'location',
  'lock',
  'locked',
  'logged',
  'mapping',
  'match',
  'materialized',
  'maxvalue',
  'method',
  'minute',
  'minvalue',
  'mode',
  'month',
  'move',
  'name',
  'names',
  'national',
  'natural',
  'nchar',
  'new',
  'next',
  'nfc',
  'nfd',
  'nfkc',
  'nfkd',
  'no',
  'none',
  'normalize',
  'normalized',
  'not',
  'null',
  'nullif',
  'numeric',
  'object',
  'of',
  'off',
  'offset',
  'oids',
  'old',
  'only',
  'on',
  'operator',
  'option',
  'options',
  'or',
  'order',
  'out',
  'outer',
  'over',
  'overlaps',
  'overlay',
  'overriding',
  'owned',
  'owner',
  'parallel',
  'parameter',
  'parser',
  'partial',
  'partition',
  'passing',
  'password',
  'placing',
  'plans',
  'policy',
  'position',
  'preceding',
  'precision',
  'prepare',
  'prepared',
  'preserve',
  'prior',
  'primary',
  'privileges',
  'procedural',
  'procedure',
  'procedures',
  'program',
  'publication',
  'quote',
  'range',
  'read',
  'real',
  'reassign',
  'recheck',
  'recursive',
  'ref',
  'references',
  'referencing',
  'refresh',
  'reindex',
  'relative',
  'release',
  'rename',
  'repeatable',
  'replace',
  'replica',
  'reset',
  'restart',
  'restrict',
  'return',
  'returning',
  'returns',
  'revoke',
  'right',
  'role',
  'rollback',
  'rollup',
  'routine',
  'routines',
  'row',
  'rows',
  'rule',
  'savepoint',
  'scalar',
  'schema',
  'schemas',
  'scroll',
  'search',
  'second',
  'security',
  'select',
  'sequence',
  'sequences',
  'serializable',
  'server',
  'session',
  'session_user',
  'set',
  'setof',
  'sets',
  'share',
  'show',
  'similar',
  'simple',
  'skip',
  'smallint',
  'snapshot',
  'some',
  'sql',
  'stable',
  'standalone',
  'start',
  'statement',
  'statistics',
  'stdin',
  'stdout',
  'storage',
  'stored',
  'strict',
  'string',
  'strip',
  'subscription',
  'support',
  'symmetric',
  'sysid',
  'system',
  'table',
  'tables',
  'tablesample',
  'tablespace',
  'temp',
  'template',
  'temporary',
  'text',
  'then',
  'ties',
  'time',
  'timestamp',
  'to',
  'trailing',
  'transaction',
  'transform',
  'treat',
  'trigger',
  'trim',
  'trusted',
  'true',
  'type',
  'types',
  'uescape',
  'unbounded',
  'uncommitted',
  'unencrypted',
  'union',
  'unique',
  'unknown',
  'unlisten',
  'unlogged',
  'until',
  'update',
  'user',
  'using',
  'vacuum',
  'valid',
  'validate',
  'validator',
  'value',
  'values',
  'variadic',
  'varying',
  'verbose',
  'version',
  'view',
  'views',
  'volatile',
  'when',
  'where',
  'window',
  'with',
  'within',
  'without',
  'work',
  'wrapper',
  'write',
  'xmlattributes',
  'xmlconcat',
  'xmlelement',
  'xmlexists',
  'xmlforest',
  'xmlnamespaces',
  'xmlparse',
  'xmlpi',
  'xmlroot',
  'xmlserialize',
  'xmltable',
  'year',
  'yes',
  'zone',
]);

export const DEFAULT_SQL_FORMAT_OPTIONS = {
  identifierEscape: 'quote',
  identifierEscapeTarget: 'minimal',
  parameterSymbol: ':',
  parameterStyle: 'named',
  indentSize: 4,
  indentChar: 'space',
  newline: 'lf',
  keywordCase: 'lower',
  commaBreak: 'before',
  valuesCommaBreak: 'before',
  andBreak: 'before',
  orBreak: 'before',
  exportComment: true,
  commentStyle: 'block',
  withClauseStyle: 'standard',
  parenthesesOneLine: true,
  indentNestedParentheses: true,
  betweenOneLine: true,
  valuesOneLine: false,
  joinOneLine: true,
  caseOneLine: false,
  subqueryOneLine: false,
  joinConditionOrderByDeclaration: false,
} as const satisfies SqlFormatterOptions;

export function loadSqlFormatOptions(rootDir: string): SqlFormatterOptions {
  const configPath = path.join(path.resolve(rootDir), 'ashiba.config.json');
  if (!existsSync(configPath)) {
    return DEFAULT_SQL_FORMAT_OPTIONS;
  }
  try {
    const parsed = JSON.parse(readFileSync(configPath, 'utf8')) as { format?: { sql?: unknown } };
    if (parsed.format?.sql && typeof parsed.format.sql === 'object' && !Array.isArray(parsed.format.sql)) {
      return { ...DEFAULT_SQL_FORMAT_OPTIONS, ...(parsed.format.sql as SqlFormatterOptions) };
    }
  } catch (error) {
    throw invalidCliInputError(
      'ASHIBA_CONFIG_JSON_PARSE_FAILED',
      'Failed to parse ashiba.config.json while loading SQL format options.',
      'Fix ashiba.config.json so it is valid JSON, or remove it to use default SQL formatting.',
      { configPath, reason: error instanceof Error ? error.message : String(error) },
    );
  }
  return DEFAULT_SQL_FORMAT_OPTIONS;
}

export function resolveGeneratedSqlFormatOptions(rootDir: string, sql: string): SqlFormatterOptions {
  const options = loadSqlFormatOptions(rootDir);
  if (!containsIdentifierRequiringQuotes(sql)) {
    return options;
  }
  return { ...options, identifierEscape: 'quote' };
}

function containsIdentifierRequiringQuotes(sql: string): boolean {
  for (const match of sql.matchAll(/"((?:[^"]|"")*)"/g)) {
    const identifier = match[1]?.replace(/""/g, '"') ?? '';
    if (requiresIdentifierQuotes(identifier)) {
      return true;
    }
  }
  return false;
}

function requiresIdentifierQuotes(identifier: string): boolean {
  const normalized = identifier.toLowerCase();
  return !/^[a-z_][a-z0-9_]*$/.test(identifier) || SQL_KEYWORDS_REQUIRING_IDENTIFIER_QUOTES.has(normalized);
}
