export const copy = {
  appName: 'Support Inbox Demo',
  inbox: '受信箱',
  tickets: 'チケット一覧',
  detail: 'チケット詳細',
  reset: 'リセット',
  search: '検索',
  refresh: '更新',
  filters: {
    status: 'ステータス',
    customerTier: '顧客ティア',
    slaState: 'SLA状態',
    language: '言語',
    channel: 'チャネル',
    tag: 'タグ',
    keyword: 'キーワード',
    sort: '並び順',
  },
  values: {
    all: 'すべて',
    vip: 'VIP',
    standard: '標準',
    open: 'オープン',
    waitingCustomer: '顧客対応待ち',
    waitingAgent: 'エージェント対応中',
    resolved: '解決済み',
    draft: '下書き',
    high: '高',
    medium: '中',
    low: '低',
    breached: '期限切れ',
    warning: '間近',
    ok: 'OK',
    none: '-',
    email: 'メール',
    chat: 'チャット',
    web: 'Web',
    ja: '日本語',
    en: 'English',
  },
  sortLabels: {
    actionRequired: 'アクション優先',
    priorityHigh: '優先度: 高い順',
    slaSoon: 'SLA期限: 早い順',
    customerReplyNew: '顧客からの返信: 新しい順',
    updatedNew: '更新日時: 新しい順',
    vipFirst: 'VIP優先',
  },
  demoCards: {
    routeTitle: '受信箱一覧 (/tickets)',
    routeBullets: [
      '実務でよく使う条件でフィルタ',
      '業務優先の並び替えを safe sort で選択',
      '最新メッセージの要点を一覧表示',
      'SLA状態を視覚的に把握',
    ],
    sortTitle: 'safe sort の例',
    sortBullets: [
      'アクション優先',
      '優先度: 高い順',
      'SLA期限: 早い順',
      '顧客からの返信: 新しい順',
      '更新日時: 新しい順',
      'VIP優先',
    ],
    valueTitle: 'このデモで伝えたい価値',
    valueBullets: [
      'SQLクライアントで確認できるSQLを資産として保つ',
      '複雑な一覧ロジックを1枚のSQLに集約',
      'optional filter と safe sort を安全に扱う',
      'DTO / Mapper / Mapper Test / Drift Check が変更に強い保守体験を支える',
      'AIが変更しても、人間がレビューすべき範囲が狭い',
    ],
    note: 'フィルタは安全なパラメータとして扱われ、SQLはSSSQLにより安全にoptional条件を適用します。',
  },
} as const;
